apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: {{ .Values.nginxPort }}
    targetPort: {{ .Values.nginxTargetPort }}
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
    upstream rfam-webcode {
        server rfam-webcode:{{ .Values.rnacentralPort }};
    }

    server {
        listen {{ .Values.nginxTargetPort }};
        access_log /dev/stdout;
        error_log /dev/stderr;

        location / {
            proxy_pass http://rfam-webcode;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;

            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
            proxy_connect_timeout 120s;
        }

        error_page 500 502 503 504 /error/;
        location /error/ {
            internal;
            proxy_pass http://rfam-webcode/error/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginxReplicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - image: nginx:1.25-alpine
          name: nginx
          resources:
            requests:
              memory: {{ .Values.nginxRequestsMemory }}
              cpu: {{ .Values.nginxRequestsCPU }}
            limits:
              memory: {{ .Values.nginxLimitsMemory }}
          ports:
            - containerPort: {{ .Values.nginxTargetPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
