apiVersion: v1
kind: Service
metadata:
  name: rfam-webcode
  labels:
    app: rfam-webcode
spec:
  ports:
  - port: {{ .Values.rnacentralPort }}
    targetPort: {{ .Values.rnacentralPort }}
    protocol: TCP
  selector:
    app: rfam-webcode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfam-webcode
spec:
  replicas: {{ .Values.rfamReplicas }}
  selector:
    matchLabels:
      app: rfam-webcode
  template:
    metadata:
      labels:
        app: rfam-webcode
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - image: ghcr.io/rfam/rfam-webcode:{{ .Values.rfamBranch }}
          name: rfam-webcode
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.rnacentralPort }}
          resources:
            requests:
              memory: {{ .Values.rfamRequestsMemory }}
              cpu: {{ .Values.rfamRequestsCPU }}
            limits:
              memory: {{ .Values.rfamLimitsMemory }}
          env:
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "{{ .Values.hostname }},rfam-webcode,localhost,*"
            - name: RFAM_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database }}
                  key: DATABASE_HOST
            - name: RFAM_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database }}
                  key: DATABASE_PORT
            - name: RFAM_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database }}
                  key: DATABASE_NAME
            - name: RFAM_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database }}
                  key: DATABASE_USER
            - name: RFAM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database }}
                  key: DATABASE_PASSWORD
          envFrom:
          - configMapRef:
              name: {{ .Values.proxy }}
      restartPolicy: Always
